openapi: 3.0.1
info:
  title: storemanagement
  description: API Definition of storemanagement
  version: 1.0.0
servers:
- url: http://localhost:8290/storemanagement
paths:
  /order/{orderId}:
    get:
      parameters:
      - name: orderId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /order:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
